### ISSUE TITLE
[GiftExchange] GiftExchange Invited view

### ISSUE THREAD

**Issue by thomasnguyen** [guardiansofthegit-collab/elecretanta#46]
- [x] If a user (logged in or not) visits a GiftExchange they are not a member of. Show a modal asking if they want to join
- [x] Conditional logic for if a user is signed in or not
- [x] Conditional logic if a user is a member of the group or not
- [x] Display different buttons on different conditional values
<img width="711" alt="Image" src="https://github.com/user-attachments/assets/95ec2646-2f06-4e17-aed4-dc2c3385b29f" />

**Comment by HoldUpFjord** [comment]
Conditional logic for userID's blocked by #41. Frontend can still be worked on.
