### ISSUE TITLE
[GiftExchange] Select GiftExchange image from predefined list

### ISSUE THREAD

**Issue by thomasnguyen** [guardiansofthegit-collab/elecretanta#68]
<img width="458" alt="Image" src="https://github.com/user-attachments/assets/1ece8d60-011d-400e-bfa1-5f7d67a22514" />

**Comment by HoldUpFjord** [comment]
- [ ] Add in preset images from unsplash
- [ ] edit existing form request to handle image strings
- [ ] store in db/ add in field for db
- [ ] render image dynamically on group exchange page.
